language: python

python:
  - 2.7
#  - 3.5

install:
  - pip install ./converter

script:
  - cd converter
  - python setup.py nosetests
  - cd ..
  - vocaloid_announcer_conv
    -s source/sources.json
    -t targets/multirotor.json
    -t targets/opentx21_system.json
    list_missing_regions
  - vocaloid_announcer_conv
    -t targets/multirotor.json
    -t targets/opentx21_system.json
    validate_filenames

notifications:
  email:
    on_success: change
    on_failure: change
